name: chatbot-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - fastapi
      - uvicorn
      - python-dotenv
      - pydantic
      - langchain
      - langchain-core
      - langchain-openai
      - langchain-deepseek
      - langchain-text-splitters
      - langsmith
      - openai
      - tiktoken
      - pyyaml
      - requests
      - tqdm
      - regex
      - sqlalchemy
